on:
  workflow_call: # Added this line to make it reusable
    inputs:
      build_mode:
        required: true
        type: string
      bundle_binaries:
        required: true
        type: boolean

# https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

jobs:

  # x86_64
  build-transpiler-on-windows-x86-64:
    name: Windows x64
    uses: ./.github/workflows/_transpiler_windows_build.yml
    with:
      build_platform: x64
      build_platform_name: x86_64
      build_mode: ${{inputs.build_mode}}
      bundle_binaries: ${{inputs.bundle_binaries}}
  build-transpiler-on-unix-like-x86-64:
    name: Unix-like x64
    uses: ./.github/workflows/_transpiler_unix_like_build.yml
    with:
      linux_system: ubuntu-latest
      mac_system: macos-13
      build_platform: x64
      build_platform_name: x86_64
      build_mode: ${{inputs.build_mode}}
      bundle_binaries: ${{inputs.bundle_binaries}}

  # x86_32
  build-transpiler-on-windows-x86-32:
    name: Windows x86
    uses: ./.github/workflows/_transpiler_windows_build.yml
    with:
      build_platform: Win32
      build_platform_name: x86_32
      build_mode: ${{inputs.build_mode}}
      bundle_binaries: ${{inputs.bundle_binaries}}
  build-transpiler-on-unix-like-x86-32:
    name: Unix-like x86
    uses: ./.github/workflows/_transpiler_unix_like_build.yml
    with:
      linux_system: ubuntu-latest
      mac_system: macos-13
      build_platform: x86
      build_platform_name: x86_32
      build_mode: ${{inputs.build_mode}}
      bundle_binaries: ${{inputs.bundle_binaries}}
      skip_for: 'macOS'

  # ARM64
#  build-transpiler-on-windows-arm64:
#    name: Windows ARM64
#    uses: ./.github/workflows/_transpiler_windows_build.yml
#    with:
#      build_platform: ARM64
#      build_platform_name: arm64
#      build_mode: ${{inputs.build_mode}}
#      bundle_binaries: ${{inputs.bundle_binaries}}
  build-transpiler-on-unix-like-arm64:
    name: Unix-like ARM64
    uses: ./.github/workflows/_transpiler_unix_like_build.yml
    with:
      linux_system: ubuntu-24.04-arm
      mac_system: macos-latest
      build_platform: ARM64
      build_platform_name: arm64
      build_mode: ${{inputs.build_mode}}
      bundle_binaries: ${{inputs.bundle_binaries}}

  #ARM32
#  build-transpiler-on-windows-arm32:
#    name: Windows ARM
#    uses: ./.github/workflows/_transpiler_windows_build.yml
#    with:
#      build_platform: ARM
#      build_platform_name: arm32
#      build_mode: ${{inputs.build_mode}}
#      bundle_binaries: ${{inputs.bundle_binaries}}
  build-transpiler-on-unix-like-arm32:
    name: Unix-like ARM
    uses: ./.github/workflows/_transpiler_unix_like_build.yml
    with:
      linux_system: ubuntu-24.04-arm
      mac_system: macos-latest
      build_platform: ARM
      build_platform_name: arm32
      build_mode: ${{inputs.build_mode}}
      bundle_binaries: ${{inputs.bundle_binaries}}
